@startuml  

class Library {
    name
    founding year 
}

class Branch {
    name
    opening time
    closing time
}

class Address {
    city
    street name
    building number
}

class Book {
    name
    genre
    serial number
    copies
}

class Author {
    firstname
    lastname
}

class Customer {
    firstname
    lastname
}

class BookLoan {
    loan date
    return date
    overdue days
}

Library "1" -> "1..*" Branch : has branch
Branch "1..*" --> "1" Address : has address
Branch "1..*" -down-> "1" Book : has book
Author "1..*" -> "*" Book : writes
Book "1..*" -down-> "*" BookLoan : is borrowed
Customer "1..*" -up-> "*" BookLoan : receives

@enduml